CREATE TABLE CUSTOMER_DETAILS (CUSTOMER_ID int, CUSTOMER_NAME VARCHAR2(50) );
CREATE TABLE TRANS_DETAILS (TRANSACTION_ID int,CUSTOMER_ID int ,TRANSACTION_DATE DATE,AMOUNT int);
INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CUSTOMER_NAME) values (101,'Aravindh');
INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CUSTOMER_NAME) values (102,'Andhonisamy');
INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CUSTOMER_NAME) values (103,'Adhiyan');
INSERT INTO TRANS_DETAILS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT) VALUES (10,101,'2024-12-22',123);
INSERT INTO TRANS_DETAILS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT) VALUES (11,102,'2024-12-22',124);
INSERT INTO TRANS_DETAILS(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT) VALUES (12,103,'2024-12-22',125);
COMMIT;